apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  volumes:
  - name: html-volume
    emptyDir: {}
  initContainers:
  - name: fetch-index
    image: curlimages/curl:latest
    command: ['curl', '-o', '/usr/share/nginx/html/index.html', 'http://example.com/index.html']
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 5
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html